site_name: Chart Gizmo
site_description: H5Gizmos Library wrapper for Chart.js
site_url: https://dineshchhantyal.github.io/chart_gizmo/
repo_url: https://github.com/dineshchhantyal/chart_gizmo

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - footnotes
  - attr_list

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Examples: examples.md
  - API Reference:
      - Overview: api/index.md
      - Charts: api/charts.md
      - Bars: api/bars.md
      - Lines: api/lines.md
      - Bubbles: api/bubbles.md
      - Histogram: api/histogram.md
  - Command Line Scripts: cli.md
