site_name: Chart Gizmo
site_url: https://dineshchhantyal.github.io/chart_gizmo/
site_author: Dinesh Chhantyal
site_description: H5Gizmos Library wrapper for Chart.js
copyright: Copyright &copy; 2023 Dinesh Chhantyal
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes

plugins:
  - search

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Examples: examples.md
  - API Reference:
      - Overview: api/index.md
      - Charts: api/charts.md
      - Bars: api/bars.md
      - Lines: api/lines.md
      - Bubbles: api/bubbles.md
      - Histogram: api/histogram.md
      - Pie: api/pie.md
  - Command Line Tools:
      - Overview: cli/index.md
      - Bar Charts: cli/bar.md
      - Line Charts: cli/line.md
      - Bubble Charts: cli/bubble.md
      - Histograms: cli/histogram.md
      - Pie Charts: cli/pie.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  version:
    provider: mike
